-- MySQL Script generated by MySQL Workbench
-- Tue 24 Jan 2017 10:49:29 PM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema komunalka
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `komunalka` ;

-- -----------------------------------------------------
-- Schema komunalka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `komunalka` DEFAULT CHARACTER SET utf8 ;
USE `komunalka` ;

-- -----------------------------------------------------
-- Table `komunalka`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `komunalka`.`category` ;

CREATE TABLE IF NOT EXISTS `komunalka`.`category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(31) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `komunalka`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `komunalka`.`unit` ;

CREATE TABLE IF NOT EXISTS `komunalka`.`unit` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `komunalka`.`meter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `komunalka`.`meter` ;

CREATE TABLE IF NOT EXISTS `komunalka`.`meter` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(31) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `unit_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_meter_unit1_idx` (`unit_id` ASC),
  INDEX `fk_meter_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_meter_unit`
    FOREIGN KEY (`unit_id`)
    REFERENCES `komunalka`.`unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_meter_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `komunalka`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `komunalka`.`indicator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `komunalka`.`indicator` ;

CREATE TABLE IF NOT EXISTS `komunalka`.`indicator` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `previous` INT(11) NULL DEFAULT NULL,
  `current` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `unit_id` INT(11) NOT NULL,
  `meter_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_indicator_unit_idx` (`unit_id` ASC),
  INDEX `fk_indicator_meter1_idx` (`meter_id` ASC),
  CONSTRAINT `fk_indicator_unit`
    FOREIGN KEY (`unit_id`)
    REFERENCES `komunalka`.`unit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_indicator_meter`
    FOREIGN KEY (`meter_id`)
    REFERENCES `komunalka`.`meter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `komunalka`.`tariff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `komunalka`.`tariff` ;

CREATE TABLE IF NOT EXISTS `komunalka`.`tariff` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nane` VARCHAR(31) NOT NULL,
  `currency` VARCHAR(15) NOT NULL,
  `begin_date` DATE NOT NULL,
  `end_date` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tariff_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_tariff_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `komunalka`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `komunalka`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `komunalka`.`user` ;

CREATE TABLE IF NOT EXISTS `komunalka`.`user` (
  `id` INT(11) NOT NULL,
  `first_name` VARCHAR(31) NOT NULL,
  `last_name` VARCHAR(31) NULL,
  `login` VARCHAR(31) NOT NULL,
  `password` VARCHAR(63) NOT NULL,
  `email` VARCHAR(31) NULL,
  `create_date` DATE NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `komunalka`.`report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `komunalka`.`report` ;

CREATE TABLE IF NOT EXISTS `komunalka`.`report` (
  `id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `description` VARCHAR(255) NULL,
  `category_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_report_category1_idx` (`category_id` ASC),
  INDEX `fk_report_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_report_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `komunalka`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `komunalka`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `komunalka`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `komunalka`.`role` ;

CREATE TABLE IF NOT EXISTS `komunalka`.`role` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `komunalka`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `komunalka`.`user_role` ;

CREATE TABLE IF NOT EXISTS `komunalka`.`user_role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_role_user1_idx` (`user_id` ASC),
  INDEX `fk_user_role_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `komunalka`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `komunalka`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
